# Generated by Django 3.0.2 on 2020-04-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvehicle',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookvehicle',
            name='booking_exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
