# Generated by Django 3.0.2 on 2020-04-27 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_auto_20200427_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvehicle',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bookvehicle',
            name='variants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
