# Generated by Django 2.2 on 2020-04-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0003_auto_20200419_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_slot',
            name='booked_time',
        ),
        migrations.DeleteModel(
            name='slot_timing',
        ),
    ]
