# Generated by Django 3.0.2 on 2020-04-28 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allModels', '0003_auto_20200427_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('chessis_no', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('variants', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=100)),
                ('exit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allModels.BookVehicle')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_allmodels_parkingexit_related', to=settings.AUTH_USER_MODEL)),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allModels.Parking_slot')),
                ('writer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_allmodels_parkingexit_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
