# Generated by Django 3.0.2 on 2020-04-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0005_parkingexit_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookvehicle',
            old_name='barcode',
            new_name='barcode_details',
        ),
        migrations.RemoveField(
            model_name='parkingexit',
            name='parking_slot',
        ),
    ]
