# Generated by Django 3.0.2 on 2020-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0005_parkingin'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingin',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
