# Generated by Django 3.0.2 on 2020-04-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0006_parkingin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingin',
            name='status',
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='Barcode_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
