# Generated by Django 3.0.2 on 2020-06-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0006_auto_20200429_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmcInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('instalation_location', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amc_start_date', models.DateTimeField()),
                ('amc_end_date', models.DateTimeField()),
                ('warranty_start_date', models.DateTimeField()),
                ('warranty_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AmcInventoryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('instalation_location', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amc_start_date', models.DateTimeField()),
                ('amc_end_date', models.DateTimeField()),
                ('warranty_start_date', models.DateTimeField()),
                ('warranty_end_date', models.DateTimeField()),
                ('amc_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allModels.AmcInventory')),
            ],
        ),
    ]
