# Generated by Django 3.0.2 on 2020-06-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0007_amcinventory_amcinventoryhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcinventoryhistory',
            name='amc_inventory',
        ),
        migrations.DeleteModel(
            name='AmcInventory',
        ),
        migrations.DeleteModel(
            name='AmcInventoryHistory',
        ),
    ]
