# Generated by Django 3.0.2 on 2020-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0007_auto_20200420_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
