# Generated by Django 3.0.2 on 2020-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0008_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
