# Generated by Django 3.0.2 on 2020-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0009_amcinventory_amcinventoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcinventory',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventory',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventory',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventory',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventoryhistory',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventoryhistory',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventoryhistory',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcinventoryhistory',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
