# Generated by Django 3.0.2 on 2020-04-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0010_parkingout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingout',
            old_name='entry_date',
            new_name='exit_date',
        ),
    ]
