# Generated by Django 3.0.2 on 2020-06-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0010_auto_20200608_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcinventoryhistory',
            name='amc_inventory',
        ),
    ]
